name: Generate changelog
on:
  release:
    types:
      - "created"
      - "edited"
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "✏️ Generate release changelog"
        id: generate
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "✏️ Update CHANGELOG.md"
        uses: wow-actions/update-file@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: CHANGELOG.md
          content: steps.generate.outputs.changelog
          commit_message: 'docs(CHANGELOG): update release notes'
